//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alerta_mantencion
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int lecheria_id { get; set; }
    
        public virtual lecheria lecheria { get; set; }
    }
}
