//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public animal()
        {
            this.gps = new HashSet<gps>();
            this.historial_gps = new HashSet<historial_gps>();
            this.inseminacion = new HashSet<inseminacion>();
            this.muerte = new HashSet<muerte>();
            this.parto = new HashSet<parto>();
            this.parto1 = new HashSet<parto>();
            this.secamiento = new HashSet<secamiento>();
            this.tratamiento_animal = new HashSet<tratamiento_animal>();
            this.venta = new HashSet<venta>();
        }
    
        public int id { get; set; }
        public string codigo_sag { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fec_nac { get; set; }
        public System.DateTime fecha_ing { get; set; }
        public int tipo_id { get; set; }
        public int raza_id { get; set; }
        public int estado_id { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual raza raza { get; set; }
        public virtual tipo tipo { get; set; }
        public virtual ICollection<gps> gps { get; set; }
        public virtual ICollection<historial_gps> historial_gps { get; set; }
        public virtual ICollection<inseminacion> inseminacion { get; set; }
        public virtual ICollection<muerte> muerte { get; set; }
        public virtual ICollection<parto> parto { get; set; }
        public virtual ICollection<parto> parto1 { get; set; }
        public virtual ICollection<secamiento> secamiento { get; set; }
        public virtual ICollection<tratamiento_animal> tratamiento_animal { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
