//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecheria
    {
        public lecheria()
        {
            this.alerta_mantencion = new HashSet<alerta_mantencion>();
            this.ordena = new HashSet<ordena>();
        }
    
        public int id { get; set; }
        public int capacidad { get; set; }
        public int ordenas_diarias { get; set; }
        public int cantidad_trabajadores { get; set; }
        public int tipo_lecheria_id { get; set; }
        public int fabricante_id { get; set; }
    
        public virtual ICollection<alerta_mantencion> alerta_mantencion { get; set; }
        public virtual fabricante fabricante { get; set; }
        public virtual tipo_lecheria tipo_lecheria { get; set; }
        public virtual ICollection<ordena> ordena { get; set; }
    }
}
