//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nace_muerto
    {
        public int id { get; set; }
        public int parto_id { get; set; }
        public int raza_id { get; set; }
        public int tipo_id { get; set; }
    
        public virtual parto parto { get; set; }
        public virtual raza raza { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
