//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.poligono = new HashSet<poligono>();
        }
    
        public int id { get; set; }
        public string rut { get; set; }
        public string clave { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<poligono> poligono { get; set; }
    }
}
